name: Howard.io
favicon: null
layout_spectrum: 0.5725900314282626
typography_spectrum: 0.07147357473149896
title: 每天都在戰鬥
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1705849024001509
  lightness: 0.9917769117746502
  saturation: 0.7615042880643159
  rhythmicContrast: 0.980889764148742
purpose: []
